In [9]:
import numpy as np
from scipy.sparse import diags, csr_matrix
import matplotlib.pyplot as plt

# Parameters
rN, t = 50, 2
h, w = 1 + 2 * t, 1 + (t + 1) // 2
o = h * (w + 1)
rule = np.array([int(x) for x in f'{rN:08b}'][::-1])


In [ ]:

# Adjacency matrix
aM = diags([1, 1, 1, 0], [-w, w + 1, 1, -1], shape=(o, o)).tocsr()

# Initial state vector
sV = csr_matrix(([1], ([o // 2 - t], [0])), shape=(o, 1))

# Evolution
for _ in range(t):
    neighbors = 4 * sV + aM @ sV
    sV = csr_matrix(rule[neighbors.toarray().astype(int)]).reshape(-1, 1)

# Plot result
plt.imshow(sV.toarray().reshape(h, w), aspect=2 / np.sqrt(3))
plt.show()


In [10]:
# Adjacency matrix
diags([1, 1, 1, 0], [-w, w + 1, 1, -1], shape=(o, o)).toarray()

array([[0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.

In [31]:
import numpy as np
from scipy.sparse import diags

# Size of the matrix
n = 10  # Adjust n to the desired size

# Create an array with alternating 1s and 0s
diagonal = np.array([1 if i % 2 == 0 else 0 for i in range(n)])

# Create a sparse matrix with the alternating diagonal
sparse_matrix = diags(diagonal, 0)

print(sparse_matrix.toarray())  # To visualize the matrix


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
np.array([1 if i % 2 == 0 else 0 for i in range(100000000)])

array([1, 0, 1, ..., 0, 1, 0])